# Generated by Django 4.1.7 on 2023-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Img', models.ImageField(upload_to='pics')),
                ('Desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
